export type SubstitutionRule = {
  from: string;
  to: string | string[];
  explanation: string;
  flavorImpact: "none" | "subtle" | "noticeable";
  safeForBaking: boolean;
  rolesPreserved: string[];
};

export const SUBSTITUTION_RULES: SubstitutionRule[] = [
  {
    from: "buttermilk",
    to: ["milk", "lemon"],
    explanation: "Milk plus a squeeze of lemon gives you the same tang and tenderness.",
    flavorImpact: "subtle",
    safeForBaking: true,
    rolesPreserved: ["acid", "moisture"],
  },
  {
    from: "buttermilk",
    to: "greek-yogurt",
    explanation: "Thin the yogurt with a splash of water. Same tang, a little thicker.",
    flavorImpact: "subtle",
    safeForBaking: true,
    rolesPreserved: ["acid", "dairy"],
  },
  {
    from: "heavy-cream",
    to: ["milk", "butter"],
    explanation: "Milk plus a knob of butter gets you close for sauces. It won't whip.",
    flavorImpact: "noticeable",
    safeForBaking: false,
    rolesPreserved: ["fat", "moisture"],
  },
  {
    from: "heavy-cream",
    to: "coconut-milk",
    explanation: "Coconut milk keeps things lush. You'll taste coconut, which can be a plus.",
    flavorImpact: "noticeable",
    safeForBaking: false,
    rolesPreserved: ["fat", "moisture"],
  },
  {
    from: "cilantro",
    to: "parsley",
    explanation: "Parsley keeps the freshness. You lose the citrusy cilantro note, but the dish still works.",
    flavorImpact: "noticeable",
    safeForBaking: true,
    rolesPreserved: ["herb"],
  },
  {
    from: "parsley",
    to: "cilantro",
    explanation: "Cilantro is brighter. Fine in savory dishes, skip it if anyone hates that flavor.",
    flavorImpact: "noticeable",
    safeForBaking: true,
    rolesPreserved: ["herb"],
  },
  {
    from: "scallion",
    to: "chives",
    explanation: "Chives give you the same gentle onion finish.",
    flavorImpact: "subtle",
    safeForBaking: true,
    rolesPreserved: ["aromatic", "herb"],
  },
  {
    from: "scallion",
    to: "onion",
    explanation: "A little raw or quickly sautéed onion covers the job. Use less than you think.",
    flavorImpact: "noticeable",
    safeForBaking: true,
    rolesPreserved: ["aromatic"],
  },
  {
    from: "lime",
    to: "lemon",
    explanation: "Lemon is a little sweeter, but you still get the acid the dish needs.",
    flavorImpact: "subtle",
    safeForBaking: true,
    rolesPreserved: ["acid"],
  },
  {
    from: "lemon",
    to: "lime",
    explanation: "Lime is sharper. It works anywhere you need a squeeze of citrus.",
    flavorImpact: "subtle",
    safeForBaking: true,
    rolesPreserved: ["acid"],
  },
  {
    from: "lemon",
    to: "vinegar",
    explanation: "A splash of vinegar covers acidity. You lose the citrus perfume.",
    flavorImpact: "noticeable",
    safeForBaking: false,
    rolesPreserved: ["acid"],
  },
  {
    from: "greek-yogurt",
    to: "sour-cream",
    explanation: "Sour cream is richer and a little less tangy. Great in sauces and on tacos.",
    flavorImpact: "subtle",
    safeForBaking: false,
    rolesPreserved: ["dairy", "acid"],
  },
  {
    from: "sour-cream",
    to: "greek-yogurt",
    explanation: "Greek yogurt works. It'll be tangier and a bit thicker — honestly, I like it.",
    flavorImpact: "subtle",
    safeForBaking: false,
    rolesPreserved: ["dairy", "acid"],
  },
  {
    from: "butter",
    to: "olive-oil",
    explanation: "Olive oil covers the fat. Flavor leans fruitier, which is fine in savory cooking.",
    flavorImpact: "noticeable",
    safeForBaking: false,
    rolesPreserved: ["fat"],
  },
  {
    from: "olive-oil",
    to: "neutral-oil",
    explanation: "Any cooking oil works here. You'll miss a little olive flavor, nothing structural.",
    flavorImpact: "subtle",
    safeForBaking: true,
    rolesPreserved: ["fat"],
  },
  {
    from: "neutral-oil",
    to: "olive-oil",
    explanation: "Olive oil is a fine stand-in for sautéing and roasting.",
    flavorImpact: "subtle",
    safeForBaking: false,
    rolesPreserved: ["fat"],
  },
  {
    from: "soy-sauce",
    to: "worcestershire",
    explanation: "Worcestershire brings salt and umami. It's not identical, but it keeps the dish from tasting flat.",
    flavorImpact: "noticeable",
    safeForBaking: true,
    rolesPreserved: ["salt", "umami"],
  },
  {
    from: "soy-sauce",
    to: "fish-sauce",
    explanation: "Use less — fish sauce is louder. Same salty-savory job.",
    flavorImpact: "noticeable",
    safeForBaking: true,
    rolesPreserved: ["salt", "umami"],
  },
  {
    from: "chicken-breast",
    to: "chicken-thigh",
    explanation: "Thighs are juicier and a little more forgiving. Same dinner, better insurance.",
    flavorImpact: "subtle",
    safeForBaking: true,
    rolesPreserved: ["protein"],
  },
  {
    from: "chicken-thigh",
    to: "chicken-breast",
    explanation: "Breast works if you don't overcook it. Pull it as soon as it's just done.",
    flavorImpact: "subtle",
    safeForBaking: true,
    rolesPreserved: ["protein"],
  },
  {
    from: "chicken-breast",
    to: "leftover-chicken",
    explanation: "Use the cooked chicken and skip the raw sear. Add it at the end so it stays tender.",
    flavorImpact: "none",
    safeForBaking: true,
    rolesPreserved: ["protein"],
  },
  {
    from: "rice",
    to: "leftover-rice",
    explanation: "Day-old rice is actually better for stir-fries and fried rice.",
    flavorImpact: "none",
    safeForBaking: true,
    rolesPreserved: ["starch"],
  },
  {
    from: "cheddar",
    to: "mozzarella",
    explanation: "Mozzarella melts beautifully and is milder. You'll miss the cheddar tang.",
    flavorImpact: "noticeable",
    safeForBaking: true,
    rolesPreserved: ["dairy", "fat"],
  },
  {
    from: "mozzarella",
    to: "cheddar",
    explanation: "Cheddar melts and brings more flavor. A little sharper, still great.",
    flavorImpact: "subtle",
    safeForBaking: true,
    rolesPreserved: ["dairy", "fat"],
  },
  {
    from: "spinach",
    to: "kale",
    explanation: "Kale needs an extra minute in the pan. Same green job, a bit chewier.",
    flavorImpact: "subtle",
    safeForBaking: true,
    rolesPreserved: ["vegetable"],
  },
  {
    from: "kale",
    to: "spinach",
    explanation: "Spinach wilts faster, so add it later. Easy swap.",
    flavorImpact: "subtle",
    safeForBaking: true,
    rolesPreserved: ["vegetable"],
  },
  {
    from: "basil",
    to: "dried-basil",
    explanation: "Use about a third as much dried basil, and add it earlier. It won't taste as bright.",
    flavorImpact: "noticeable",
    safeForBaking: true,
    rolesPreserved: ["herb"],
  },
  {
    from: "milk",
    to: "greek-yogurt",
    explanation: "Loosen yogurt with water until it pours. Tangier, still creamy.",
    flavorImpact: "noticeable",
    safeForBaking: false,
    rolesPreserved: ["dairy", "moisture"],
  },
  {
    from: "stock",
    to: "water",
    explanation: "Water works in a pinch. Season a little more assertively.",
    flavorImpact: "noticeable",
    safeForBaking: true,
    rolesPreserved: ["moisture"],
  },
];
