import type { CanonicalIngredient } from "@/domain/types";

function item(
  partial: Omit<CanonicalIngredient, "aliases" | "roles" | "allergens"> &
    Partial<Pick<CanonicalIngredient, "aliases" | "roles" | "allergens">>,
): CanonicalIngredient {
  return {
    aliases: [],
    roles: [],
    allergens: [],
    ...partial,
  };
}

export const INGREDIENT_CATALOG: CanonicalIngredient[] = [
  item({
    id: "chicken-breast",
    name: "chicken breast",
    aliases: ["chicken", "chicken breasts", "boneless chicken", "chicken tenders"],
    category: "protein",
    typicalLocation: "fridge",
    perishabilityDays: 2,
    staple: false,
    family: "chicken",
    roles: ["protein"],
    estimatedCost: "medium",
    versatility: 0.95,
    bakingSensitive: false,
  }),
  item({
    id: "chicken-thigh",
    name: "chicken thigh",
    aliases: ["chicken thighs", "thighs"],
    category: "protein",
    typicalLocation: "fridge",
    perishabilityDays: 2,
    staple: false,
    family: "chicken",
    roles: ["protein"],
    estimatedCost: "medium",
    versatility: 0.9,
    bakingSensitive: false,
  }),
  item({
    id: "ground-beef",
    name: "ground beef",
    aliases: ["beef", "mince", "hamburger meat", "ground meat"],
    category: "protein",
    typicalLocation: "fridge",
    perishabilityDays: 2,
    staple: false,
    family: "beef",
    roles: ["protein"],
    estimatedCost: "medium",
    versatility: 0.85,
    bakingSensitive: false,
  }),
  item({
    id: "eggs",
    name: "eggs",
    aliases: ["egg", "large eggs", "chicken eggs"],
    category: "protein",
    typicalLocation: "fridge",
    perishabilityDays: 21,
    staple: true,
    family: "egg",
    roles: ["protein", "binder"],
    allergens: ["egg"],
    estimatedCost: "low",
    versatility: 1,
    bakingSensitive: true,
  }),
  item({
    id: "tofu",
    name: "tofu",
    aliases: ["firm tofu", "extra firm tofu"],
    category: "protein",
    typicalLocation: "fridge",
    perishabilityDays: 5,
    staple: false,
    family: "soy-protein",
    roles: ["protein"],
    allergens: ["soy"],
    estimatedCost: "low",
    versatility: 0.8,
    bakingSensitive: false,
  }),
  item({
    id: "canned-chickpeas",
    name: "chickpeas",
    aliases: ["garbanzo beans", "garbanzos", "canned chickpeas"],
    category: "protein",
    typicalLocation: "pantry",
    perishabilityDays: 365,
    staple: true,
    family: "legume",
    roles: ["protein", "starch"],
    estimatedCost: "low",
    versatility: 0.85,
    bakingSensitive: false,
  }),
  item({
    id: "black-beans",
    name: "black beans",
    aliases: ["canned black beans"],
    category: "protein",
    typicalLocation: "pantry",
    perishabilityDays: 365,
    staple: true,
    family: "legume",
    roles: ["protein", "starch"],
    estimatedCost: "low",
    versatility: 0.8,
    bakingSensitive: false,
  }),
  item({
    id: "shrimp",
    name: "shrimp",
    aliases: ["prawns", "frozen shrimp"],
    category: "protein",
    typicalLocation: "freezer",
    perishabilityDays: 2,
    staple: false,
    family: "shellfish",
    roles: ["protein"],
    allergens: ["shellfish"],
    estimatedCost: "high",
    versatility: 0.7,
    bakingSensitive: false,
  }),
  item({
    id: "salmon",
    name: "salmon",
    aliases: ["salmon fillet", "salmon filet"],
    category: "protein",
    typicalLocation: "fridge",
    perishabilityDays: 2,
    staple: false,
    family: "fish",
    roles: ["protein"],
    allergens: ["fish"],
    estimatedCost: "high",
    versatility: 0.65,
    bakingSensitive: false,
  }),
  item({
    id: "bacon",
    name: "bacon",
    aliases: ["bacon strips"],
    category: "protein",
    typicalLocation: "fridge",
    perishabilityDays: 7,
    staple: false,
    family: "pork",
    roles: ["protein", "fat", "salt"],
    estimatedCost: "medium",
    versatility: 0.7,
    bakingSensitive: false,
  }),
  item({
    id: "spinach",
    name: "spinach",
    aliases: ["baby spinach", "fresh spinach"],
    category: "produce",
    typicalLocation: "fridge",
    perishabilityDays: 4,
    staple: false,
    family: "leafy-green",
    roles: ["vegetable"],
    estimatedCost: "low",
    versatility: 0.85,
    bakingSensitive: false,
  }),
  item({
    id: "kale",
    name: "kale",
    aliases: ["tuscan kale", "lacinato kale"],
    category: "produce",
    typicalLocation: "fridge",
    perishabilityDays: 5,
    staple: false,
    family: "leafy-green",
    roles: ["vegetable"],
    estimatedCost: "low",
    versatility: 0.7,
    bakingSensitive: false,
  }),
  item({
    id: "lettuce",
    name: "lettuce",
    aliases: ["romaine", "iceberg", "salad greens", "mixed greens"],
    category: "produce",
    typicalLocation: "fridge",
    perishabilityDays: 5,
    staple: false,
    family: "leafy-green",
    roles: ["vegetable"],
    estimatedCost: "low",
    versatility: 0.6,
    bakingSensitive: false,
  }),
  item({
    id: "tomato",
    name: "tomato",
    aliases: ["tomatoes", "roma tomato", "cherry tomatoes", "grape tomatoes"],
    category: "produce",
    typicalLocation: "counter",
    perishabilityDays: 5,
    staple: false,
    family: "tomato",
    roles: ["vegetable", "acid", "moisture"],
    estimatedCost: "low",
    versatility: 0.9,
    bakingSensitive: false,
  }),
  item({
    id: "canned-tomatoes",
    name: "canned tomatoes",
    aliases: ["crushed tomatoes", "diced tomatoes", "tomato sauce", "passata"],
    category: "pantry",
    typicalLocation: "pantry",
    perishabilityDays: 365,
    staple: true,
    family: "tomato",
    roles: ["vegetable", "acid", "moisture"],
    estimatedCost: "low",
    versatility: 0.85,
    bakingSensitive: false,
  }),
  item({
    id: "onion",
    name: "onion",
    aliases: ["onions", "yellow onion", "white onion", "red onion"],
    category: "produce",
    typicalLocation: "pantry",
    perishabilityDays: 21,
    staple: true,
    family: "allium",
    roles: ["aromatic"],
    estimatedCost: "low",
    versatility: 1,
    bakingSensitive: false,
  }),
  item({
    id: "garlic",
    name: "garlic",
    aliases: ["garlic cloves", "fresh garlic", "garlic bulb"],
    category: "produce",
    typicalLocation: "pantry",
    perishabilityDays: 30,
    staple: true,
    family: "allium",
    roles: ["aromatic"],
    estimatedCost: "low",
    versatility: 1,
    bakingSensitive: false,
  }),
  item({
    id: "scallion",
    name: "scallions",
    aliases: ["green onions", "spring onions", "green onion", "scallion"],
    category: "produce",
    typicalLocation: "fridge",
    perishabilityDays: 7,
    staple: false,
    family: "allium-green",
    roles: ["aromatic", "herb"],
    estimatedCost: "low",
    versatility: 0.75,
    bakingSensitive: false,
  }),
  item({
    id: "bell-pepper",
    name: "bell pepper",
    aliases: ["pepper", "peppers", "red pepper", "red bell pepper", "capsicum", "green pepper", "yellow pepper"],
    category: "produce",
    typicalLocation: "fridge",
    perishabilityDays: 7,
    staple: false,
    family: "pepper",
    roles: ["vegetable"],
    estimatedCost: "low",
    versatility: 0.85,
    bakingSensitive: false,
  }),
  item({
    id: "jalapeno",
    name: "jalapeño",
    aliases: ["jalapeno", "jalapeños", "hot pepper"],
    category: "produce",
    typicalLocation: "fridge",
    perishabilityDays: 10,
    staple: false,
    family: "chili",
    roles: ["spice"],
    estimatedCost: "low",
    versatility: 0.55,
    bakingSensitive: false,
  }),
  item({
    id: "carrot",
    name: "carrot",
    aliases: ["carrots"],
    category: "produce",
    typicalLocation: "fridge",
    perishabilityDays: 21,
    staple: true,
    family: "root",
    roles: ["vegetable", "sweet"],
    estimatedCost: "low",
    versatility: 0.8,
    bakingSensitive: false,
  }),
  item({
    id: "celery",
    name: "celery",
    aliases: ["celery stalks"],
    category: "produce",
    typicalLocation: "fridge",
    perishabilityDays: 14,
    staple: false,
    family: "aromatic-veg",
    roles: ["vegetable", "aromatic"],
    estimatedCost: "low",
    versatility: 0.6,
    bakingSensitive: false,
  }),
  item({
    id: "potato",
    name: "potato",
    aliases: ["potatoes", "russet", "yukon gold", "baby potatoes"],
    category: "produce",
    typicalLocation: "pantry",
    perishabilityDays: 21,
    staple: true,
    family: "potato",
    roles: ["starch"],
    estimatedCost: "low",
    versatility: 0.9,
    bakingSensitive: false,
  }),
  item({
    id: "sweet-potato",
    name: "sweet potato",
    aliases: ["sweet potatoes", "yam"],
    category: "produce",
    typicalLocation: "pantry",
    perishabilityDays: 14,
    staple: false,
    family: "potato",
    roles: ["starch", "sweet"],
    estimatedCost: "low",
    versatility: 0.7,
    bakingSensitive: false,
  }),
  item({
    id: "avocado",
    name: "avocado",
    aliases: ["avocados", "hass avocado"],
    category: "produce",
    typicalLocation: "counter",
    perishabilityDays: 4,
    staple: false,
    family: "avocado",
    roles: ["fat", "vegetable"],
    estimatedCost: "medium",
    versatility: 0.7,
    bakingSensitive: false,
  }),
  item({
    id: "lime",
    name: "lime",
    aliases: ["limes", "lime juice"],
    category: "produce",
    typicalLocation: "fridge",
    perishabilityDays: 14,
    staple: false,
    family: "citrus",
    roles: ["acid"],
    estimatedCost: "low",
    versatility: 0.8,
    bakingSensitive: false,
  }),
  item({
    id: "lemon",
    name: "lemon",
    aliases: ["lemons", "lemon juice"],
    category: "produce",
    typicalLocation: "fridge",
    perishabilityDays: 14,
    staple: false,
    family: "citrus",
    roles: ["acid"],
    estimatedCost: "low",
    versatility: 0.85,
    bakingSensitive: false,
  }),
  item({
    id: "mushroom",
    name: "mushrooms",
    aliases: ["mushroom", "cremini", "button mushrooms", "baby bella"],
    category: "produce",
    typicalLocation: "fridge",
    perishabilityDays: 5,
    staple: false,
    family: "mushroom",
    roles: ["vegetable", "umami"],
    estimatedCost: "medium",
    versatility: 0.75,
    bakingSensitive: false,
  }),
  item({
    id: "broccoli",
    name: "broccoli",
    aliases: ["broccoli florets"],
    category: "produce",
    typicalLocation: "fridge",
    perishabilityDays: 6,
    staple: false,
    family: "cruciferous",
    roles: ["vegetable"],
    estimatedCost: "low",
    versatility: 0.7,
    bakingSensitive: false,
  }),
  item({
    id: "zucchini",
    name: "zucchini",
    aliases: ["courgette", "summer squash"],
    category: "produce",
    typicalLocation: "fridge",
    perishabilityDays: 6,
    staple: false,
    family: "squash",
    roles: ["vegetable", "moisture"],
    estimatedCost: "low",
    versatility: 0.7,
    bakingSensitive: false,
  }),
  item({
    id: "cucumber",
    name: "cucumber",
    aliases: ["cucumbers"],
    category: "produce",
    typicalLocation: "fridge",
    perishabilityDays: 7,
    staple: false,
    family: "cucumber",
    roles: ["vegetable"],
    estimatedCost: "low",
    versatility: 0.5,
    bakingSensitive: false,
  }),
  item({
    id: "ginger",
    name: "ginger",
    aliases: ["fresh ginger", "ginger root"],
    category: "produce",
    typicalLocation: "fridge",
    perishabilityDays: 21,
    staple: false,
    family: "ginger",
    roles: ["aromatic", "spice"],
    estimatedCost: "low",
    versatility: 0.75,
    bakingSensitive: false,
  }),
  item({
    id: "cilantro",
    name: "cilantro",
    aliases: ["coriander", "fresh cilantro", "fresh coriander"],
    category: "produce",
    typicalLocation: "fridge",
    perishabilityDays: 5,
    staple: false,
    family: "fresh-herb",
    roles: ["herb"],
    estimatedCost: "low",
    versatility: 0.65,
    bakingSensitive: false,
  }),
  item({
    id: "parsley",
    name: "parsley",
    aliases: ["fresh parsley", "flat leaf parsley", "italian parsley"],
    category: "produce",
    typicalLocation: "fridge",
    perishabilityDays: 7,
    staple: false,
    family: "fresh-herb",
    roles: ["herb"],
    estimatedCost: "low",
    versatility: 0.7,
    bakingSensitive: false,
  }),
  item({
    id: "basil",
    name: "fresh basil",
    aliases: ["basil", "thai basil", "sweet basil"],
    category: "produce",
    typicalLocation: "fridge",
    perishabilityDays: 4,
    staple: false,
    family: "basil",
    roles: ["herb"],
    estimatedCost: "medium",
    versatility: 0.65,
    bakingSensitive: false,
  }),
  item({
    id: "dried-basil",
    name: "dried basil",
    aliases: ["basil dried"],
    category: "spice",
    typicalLocation: "pantry",
    perishabilityDays: 365,
    staple: true,
    family: "basil",
    roles: ["herb"],
    estimatedCost: "low",
    versatility: 0.4,
    bakingSensitive: false,
  }),
  item({
    id: "milk",
    name: "milk",
    aliases: ["whole milk", "2% milk", "2 percent milk", "reduced fat milk"],
    category: "dairy",
    typicalLocation: "fridge",
    perishabilityDays: 7,
    staple: true,
    family: "milk",
    roles: ["dairy", "moisture"],
    allergens: ["dairy"],
    estimatedCost: "low",
    versatility: 0.9,
    bakingSensitive: true,
  }),
  item({
    id: "heavy-cream",
    name: "heavy cream",
    aliases: ["whipping cream", "double cream", "heavy whipping cream"],
    category: "dairy",
    typicalLocation: "fridge",
    perishabilityDays: 10,
    staple: false,
    family: "cream",
    roles: ["dairy", "fat", "moisture"],
    allergens: ["dairy"],
    estimatedCost: "medium",
    versatility: 0.7,
    bakingSensitive: true,
  }),
  item({
    id: "butter",
    name: "butter",
    aliases: ["unsalted butter", "salted butter"],
    category: "dairy",
    typicalLocation: "fridge",
    perishabilityDays: 30,
    staple: true,
    family: "butter",
    roles: ["fat", "dairy"],
    allergens: ["dairy"],
    estimatedCost: "low",
    versatility: 1,
    bakingSensitive: true,
  }),
  item({
    id: "cheddar",
    name: "cheddar",
    aliases: ["cheddar cheese", "shredded cheddar", "sharp cheddar"],
    category: "dairy",
    typicalLocation: "fridge",
    perishabilityDays: 21,
    staple: false,
    family: "cheese",
    roles: ["dairy", "fat", "salt"],
    allergens: ["dairy"],
    estimatedCost: "medium",
    versatility: 0.85,
    bakingSensitive: false,
  }),
  item({
    id: "mozzarella",
    name: "mozzarella",
    aliases: ["mozzarella cheese", "shredded mozzarella"],
    category: "dairy",
    typicalLocation: "fridge",
    perishabilityDays: 14,
    staple: false,
    family: "cheese",
    roles: ["dairy", "fat"],
    allergens: ["dairy"],
    estimatedCost: "medium",
    versatility: 0.75,
    bakingSensitive: false,
  }),
  item({
    id: "parmesan",
    name: "parmesan",
    aliases: ["parmigiano", "parmigiano-reggiano", "grated parmesan"],
    category: "dairy",
    typicalLocation: "fridge",
    perishabilityDays: 45,
    staple: false,
    family: "hard-cheese",
    roles: ["dairy", "salt", "umami"],
    allergens: ["dairy"],
    estimatedCost: "medium",
    versatility: 0.8,
    bakingSensitive: false,
  }),
  item({
    id: "feta",
    name: "feta",
    aliases: ["feta cheese"],
    category: "dairy",
    typicalLocation: "fridge",
    perishabilityDays: 14,
    staple: false,
    family: "cheese",
    roles: ["dairy", "salt"],
    allergens: ["dairy"],
    estimatedCost: "medium",
    versatility: 0.6,
    bakingSensitive: false,
  }),
  item({
    id: "greek-yogurt",
    name: "Greek yogurt",
    aliases: ["yogurt", "plain yogurt", "greek yoghurt"],
    category: "dairy",
    typicalLocation: "fridge",
    perishabilityDays: 14,
    staple: false,
    family: "yogurt",
    roles: ["dairy", "acid", "protein"],
    allergens: ["dairy"],
    estimatedCost: "low",
    versatility: 0.8,
    bakingSensitive: true,
  }),
  item({
    id: "sour-cream",
    name: "sour cream",
    aliases: ["soured cream"],
    category: "dairy",
    typicalLocation: "fridge",
    perishabilityDays: 14,
    staple: false,
    family: "cultured-cream",
    roles: ["dairy", "acid", "fat"],
    allergens: ["dairy"],
    estimatedCost: "low",
    versatility: 0.65,
    bakingSensitive: false,
  }),
  item({
    id: "cream-cheese",
    name: "cream cheese",
    aliases: ["philadelphia"],
    category: "dairy",
    typicalLocation: "fridge",
    perishabilityDays: 21,
    staple: false,
    family: "cream-cheese",
    roles: ["dairy", "fat"],
    allergens: ["dairy"],
    estimatedCost: "medium",
    versatility: 0.55,
    bakingSensitive: true,
  }),
  item({
    id: "rice",
    name: "rice",
    aliases: ["white rice", "jasmine rice", "basmati", "long grain rice"],
    category: "grain",
    typicalLocation: "pantry",
    perishabilityDays: 365,
    staple: true,
    family: "rice",
    roles: ["starch"],
    estimatedCost: "low",
    versatility: 0.95,
    bakingSensitive: false,
  }),
  item({
    id: "pasta",
    name: "pasta",
    aliases: ["spaghetti", "noodles", "penne", "linguine", "fettuccine"],
    category: "grain",
    typicalLocation: "pantry",
    perishabilityDays: 365,
    staple: true,
    family: "wheat-pasta",
    roles: ["starch"],
    allergens: ["gluten"],
    estimatedCost: "low",
    versatility: 0.9,
    bakingSensitive: false,
  }),
  item({
    id: "tortilla",
    name: "tortillas",
    aliases: ["tortilla", "flour tortillas", "corn tortillas", "wraps"],
    category: "bakery",
    typicalLocation: "fridge",
    perishabilityDays: 14,
    staple: false,
    family: "flatbread",
    roles: ["starch"],
    estimatedCost: "low",
    versatility: 0.9,
    bakingSensitive: false,
  }),
  item({
    id: "bread",
    name: "bread",
    aliases: ["sandwich bread", "loaf", "sourdough"],
    category: "bakery",
    typicalLocation: "counter",
    perishabilityDays: 5,
    staple: false,
    family: "bread",
    roles: ["starch"],
    allergens: ["gluten"],
    estimatedCost: "low",
    versatility: 0.75,
    bakingSensitive: false,
  }),
  item({
    id: "flour",
    name: "flour",
    aliases: ["all-purpose flour", "all purpose flour", "ap flour"],
    category: "pantry",
    typicalLocation: "pantry",
    perishabilityDays: 180,
    staple: true,
    family: "flour",
    roles: ["starch", "thickener"],
    allergens: ["gluten"],
    estimatedCost: "low",
    versatility: 0.85,
    bakingSensitive: true,
  }),
  item({
    id: "oats",
    name: "oats",
    aliases: ["rolled oats", "oatmeal"],
    category: "grain",
    typicalLocation: "pantry",
    perishabilityDays: 180,
    staple: true,
    family: "oat",
    roles: ["starch"],
    estimatedCost: "low",
    versatility: 0.6,
    bakingSensitive: false,
  }),
  item({
    id: "olive-oil",
    name: "olive oil",
    aliases: ["extra virgin olive oil", "evoo"],
    category: "pantry",
    typicalLocation: "pantry",
    perishabilityDays: 365,
    staple: true,
    family: "oil",
    roles: ["fat"],
    estimatedCost: "medium",
    versatility: 1,
    bakingSensitive: false,
  }),
  item({
    id: "neutral-oil",
    name: "neutral oil",
    aliases: ["vegetable oil", "canola oil", "avocado oil", "grapeseed oil"],
    category: "pantry",
    typicalLocation: "pantry",
    perishabilityDays: 365,
    staple: true,
    family: "oil",
    roles: ["fat"],
    estimatedCost: "low",
    versatility: 0.95,
    bakingSensitive: false,
  }),
  item({
    id: "sesame-oil",
    name: "sesame oil",
    aliases: ["toasted sesame oil"],
    category: "condiment",
    typicalLocation: "pantry",
    perishabilityDays: 365,
    staple: false,
    family: "oil",
    roles: ["fat", "aromatic"],
    allergens: ["sesame"],
    estimatedCost: "medium",
    versatility: 0.5,
    bakingSensitive: false,
  }),
  item({
    id: "soy-sauce",
    name: "soy sauce",
    aliases: ["soya sauce", "shoyu", "tamari"],
    category: "condiment",
    typicalLocation: "pantry",
    perishabilityDays: 365,
    staple: true,
    family: "soy-sauce",
    roles: ["salt", "umami"],
    allergens: ["soy", "gluten"],
    estimatedCost: "low",
    versatility: 0.85,
    bakingSensitive: false,
  }),
  item({
    id: "fish-sauce",
    name: "fish sauce",
    aliases: [],
    category: "condiment",
    typicalLocation: "pantry",
    perishabilityDays: 365,
    staple: false,
    family: "umami-sauce",
    roles: ["salt", "umami"],
    allergens: ["fish"],
    estimatedCost: "low",
    versatility: 0.45,
    bakingSensitive: false,
  }),
  item({
    id: "worcestershire",
    name: "Worcestershire sauce",
    aliases: ["worcestershire"],
    category: "condiment",
    typicalLocation: "pantry",
    perishabilityDays: 365,
    staple: false,
    family: "umami-sauce",
    roles: ["umami", "salt"],
    estimatedCost: "low",
    versatility: 0.5,
    bakingSensitive: false,
  }),
  item({
    id: "hot-sauce",
    name: "hot sauce",
    aliases: ["tabasco", "sriracha", "chili sauce"],
    category: "condiment",
    typicalLocation: "fridge",
    perishabilityDays: 180,
    staple: false,
    family: "hot-sauce",
    roles: ["spice", "acid"],
    estimatedCost: "low",
    versatility: 0.6,
    bakingSensitive: false,
  }),
  item({
    id: "salsa",
    name: "salsa",
    aliases: ["pico de gallo"],
    category: "condiment",
    typicalLocation: "fridge",
    perishabilityDays: 14,
    staple: false,
    family: "salsa",
    roles: ["acid", "vegetable"],
    estimatedCost: "low",
    versatility: 0.55,
    bakingSensitive: false,
  }),
  item({
    id: "ketchup",
    name: "ketchup",
    aliases: ["catsup"],
    category: "condiment",
    typicalLocation: "fridge",
    perishabilityDays: 180,
    staple: true,
    family: "tomato-condiment",
    roles: ["sweet", "acid"],
    estimatedCost: "low",
    versatility: 0.4,
    bakingSensitive: false,
  }),
  item({
    id: "mayonnaise",
    name: "mayonnaise",
    aliases: ["mayo"],
    category: "condiment",
    typicalLocation: "fridge",
    perishabilityDays: 60,
    staple: true,
    family: "mayo",
    roles: ["fat", "emulsifier"],
    allergens: ["egg"],
    estimatedCost: "low",
    versatility: 0.6,
    bakingSensitive: false,
  }),
  item({
    id: "mustard",
    name: "mustard",
    aliases: ["dijon", "dijon mustard", "yellow mustard"],
    category: "condiment",
    typicalLocation: "fridge",
    perishabilityDays: 180,
    staple: true,
    family: "mustard",
    roles: ["acid", "spice"],
    estimatedCost: "low",
    versatility: 0.55,
    bakingSensitive: false,
  }),
  item({
    id: "vinegar",
    name: "vinegar",
    aliases: ["white vinegar", "apple cider vinegar", "red wine vinegar"],
    category: "pantry",
    typicalLocation: "pantry",
    perishabilityDays: 730,
    staple: true,
    family: "vinegar",
    roles: ["acid"],
    estimatedCost: "low",
    versatility: 0.8,
    bakingSensitive: true,
  }),
  item({
    id: "rice-vinegar",
    name: "rice vinegar",
    aliases: ["rice wine vinegar"],
    category: "pantry",
    typicalLocation: "pantry",
    perishabilityDays: 730,
    staple: false,
    family: "vinegar",
    roles: ["acid"],
    estimatedCost: "low",
    versatility: 0.55,
    bakingSensitive: false,
  }),
  item({
    id: "honey",
    name: "honey",
    aliases: [],
    category: "pantry",
    typicalLocation: "pantry",
    perishabilityDays: 730,
    staple: true,
    family: "sweetener",
    roles: ["sweet"],
    estimatedCost: "low",
    versatility: 0.7,
    bakingSensitive: true,
  }),
  item({
    id: "sugar",
    name: "sugar",
    aliases: ["white sugar", "granulated sugar", "brown sugar"],
    category: "pantry",
    typicalLocation: "pantry",
    perishabilityDays: 730,
    staple: true,
    family: "sweetener",
    roles: ["sweet"],
    estimatedCost: "low",
    versatility: 0.75,
    bakingSensitive: true,
  }),
  item({
    id: "peanut-butter",
    name: "peanut butter",
    aliases: ["pb"],
    category: "pantry",
    typicalLocation: "pantry",
    perishabilityDays: 180,
    staple: true,
    family: "nut-butter",
    roles: ["fat", "protein"],
    allergens: ["peanut"],
    estimatedCost: "low",
    versatility: 0.6,
    bakingSensitive: false,
  }),
  item({
    id: "coconut-milk",
    name: "coconut milk",
    aliases: ["canned coconut milk"],
    category: "pantry",
    typicalLocation: "pantry",
    perishabilityDays: 365,
    staple: false,
    family: "coconut",
    roles: ["fat", "moisture"],
    estimatedCost: "low",
    versatility: 0.65,
    bakingSensitive: false,
  }),
  item({
    id: "stock",
    name: "chicken stock",
    aliases: ["chicken broth", "broth", "vegetable broth", "stock"],
    category: "pantry",
    typicalLocation: "pantry",
    perishabilityDays: 365,
    staple: true,
    family: "stock",
    roles: ["moisture", "umami"],
    estimatedCost: "low",
    versatility: 0.8,
    bakingSensitive: false,
  }),
  item({
    id: "salt",
    name: "salt",
    aliases: ["kosher salt", "sea salt", "table salt"],
    category: "spice",
    typicalLocation: "pantry",
    perishabilityDays: null,
    staple: true,
    family: "salt",
    roles: ["salt"],
    estimatedCost: "low",
    versatility: 1,
    bakingSensitive: true,
  }),
  item({
    id: "black-pepper",
    name: "black pepper",
    aliases: ["pepper", "ground pepper"],
    category: "spice",
    typicalLocation: "pantry",
    perishabilityDays: null,
    staple: true,
    family: "pepper-spice",
    roles: ["spice"],
    estimatedCost: "low",
    versatility: 1,
    bakingSensitive: false,
  }),
  item({
    id: "chili-flake",
    name: "chili flakes",
    aliases: ["red pepper flakes", "crushed red pepper"],
    category: "spice",
    typicalLocation: "pantry",
    perishabilityDays: 365,
    staple: true,
    family: "chili",
    roles: ["spice"],
    estimatedCost: "low",
    versatility: 0.7,
    bakingSensitive: false,
  }),
  item({
    id: "cumin",
    name: "cumin",
    aliases: ["ground cumin"],
    category: "spice",
    typicalLocation: "pantry",
    perishabilityDays: 365,
    staple: true,
    family: "warm-spice",
    roles: ["spice"],
    estimatedCost: "low",
    versatility: 0.7,
    bakingSensitive: false,
  }),
  item({
    id: "paprika",
    name: "paprika",
    aliases: ["smoked paprika", "sweet paprika"],
    category: "spice",
    typicalLocation: "pantry",
    perishabilityDays: 365,
    staple: true,
    family: "warm-spice",
    roles: ["spice"],
    estimatedCost: "low",
    versatility: 0.7,
    bakingSensitive: false,
  }),
  item({
    id: "oregano",
    name: "oregano",
    aliases: ["dried oregano"],
    category: "spice",
    typicalLocation: "pantry",
    perishabilityDays: 365,
    staple: true,
    family: "dried-herb",
    roles: ["herb"],
    estimatedCost: "low",
    versatility: 0.6,
    bakingSensitive: false,
  }),
  item({
    id: "cinnamon",
    name: "cinnamon",
    aliases: ["ground cinnamon"],
    category: "spice",
    typicalLocation: "pantry",
    perishabilityDays: 365,
    staple: true,
    family: "sweet-spice",
    roles: ["spice", "sweet"],
    estimatedCost: "low",
    versatility: 0.5,
    bakingSensitive: false,
  }),
  item({
    id: "sesame-seeds",
    name: "sesame seeds",
    aliases: ["sesame"],
    category: "spice",
    typicalLocation: "pantry",
    perishabilityDays: 365,
    staple: false,
    family: "seed",
    roles: ["fat"],
    allergens: ["sesame"],
    estimatedCost: "low",
    versatility: 0.4,
    bakingSensitive: false,
  }),
  item({
    id: "chives",
    name: "chives",
    aliases: ["fresh chives"],
    category: "produce",
    typicalLocation: "fridge",
    perishabilityDays: 7,
    staple: false,
    family: "allium-green",
    roles: ["herb", "aromatic"],
    estimatedCost: "low",
    versatility: 0.5,
    bakingSensitive: false,
  }),
  item({
    id: "buttermilk",
    name: "buttermilk",
    aliases: [],
    category: "dairy",
    typicalLocation: "fridge",
    perishabilityDays: 14,
    staple: false,
    family: "cultured-milk",
    roles: ["dairy", "acid", "moisture"],
    allergens: ["dairy"],
    estimatedCost: "low",
    versatility: 0.45,
    bakingSensitive: true,
  }),
  item({
    id: "corn",
    name: "corn",
    aliases: ["frozen corn", "corn kernels", "canned corn"],
    category: "produce",
    typicalLocation: "freezer",
    perishabilityDays: 180,
    staple: false,
    family: "corn",
    roles: ["vegetable", "sweet"],
    estimatedCost: "low",
    versatility: 0.6,
    bakingSensitive: false,
  }),
  item({
    id: "peas",
    name: "peas",
    aliases: ["frozen peas", "green peas"],
    category: "produce",
    typicalLocation: "freezer",
    perishabilityDays: 180,
    staple: false,
    family: "legume",
    roles: ["vegetable"],
    estimatedCost: "low",
    versatility: 0.55,
    bakingSensitive: false,
  }),
  item({
    id: "leftover-rice",
    name: "cooked rice",
    aliases: ["leftover rice", "day old rice"],
    category: "leftover",
    typicalLocation: "fridge",
    perishabilityDays: 3,
    staple: false,
    family: "rice",
    roles: ["starch"],
    estimatedCost: "low",
    versatility: 0.8,
    bakingSensitive: false,
  }),
  item({
    id: "leftover-chicken",
    name: "cooked chicken",
    aliases: ["leftover chicken", "rotisserie chicken"],
    category: "leftover",
    typicalLocation: "fridge",
    perishabilityDays: 3,
    staple: false,
    family: "chicken",
    roles: ["protein"],
    estimatedCost: "medium",
    versatility: 0.9,
    bakingSensitive: false,
  }),
  item({
    id: "leftover-vegetables",
    name: "cooked vegetables",
    aliases: ["leftover vegetables", "leftover veggies"],
    category: "leftover",
    typicalLocation: "fridge",
    perishabilityDays: 3,
    staple: false,
    family: "mixed-veg",
    roles: ["vegetable"],
    estimatedCost: "low",
    versatility: 0.7,
    bakingSensitive: false,
  }),
];

const byId = new Map(INGREDIENT_CATALOG.map((item) => [item.id, item]));

export function getIngredient(id: string) {
  return byId.get(id);
}

export function allIngredients() {
  return INGREDIENT_CATALOG;
}

export const DEFAULT_PANTRY_STAPLES = [
  "salt",
  "black-pepper",
  "olive-oil",
  "neutral-oil",
];
